// ----------------------------------------------------------------------------------------------------
// Init
// ----------------------------------------------------------------------------------------------------
export const ACTION_INIT_SET_DONE = "ACTION_INIT_SET_DONE"
export const ACTION_INIT_UNSET_DONE = "ACTION_INIT_UNSET_DONE"
export const ACTION_INIT_HANDLE_COUNT = "ACTION_INIT_HANDLE_COUNT"

export const ACTION_CURRENT_RESERVATION_SET_DATE =
  "ACTION_CURRENT_RESERVATION_SET_DATE"

export const ACTION_CURRENT_RESERVATION_SET_PASSANGERS =
  "ACTION_CURRENT_RESERVATION_SET_PASSANGERS"

export const ACTION_CURRENT_RESERVATION_RESET_PASSANGERS =
  "ACTION_CURRENT_RESERVATION_RESET_PASSANGERS"

export const ACTION_BOOKED_PASSANGERS_SET_PASSANGERS =
  "ACTION_BOOKED_PASSANGERS_SET_PASSANGERS"

export const ACTION_BOOKED_PASSANGERS_REMOVE_PASSANGER =
  "ACTION_BOOKED_PASSANGERS_REMOVE_PASSANGER"

export const ACTION_BOOKED_PASSANGERS_UPDATE_PASSANGER =
  "ACTION_BOOKED_PASSANGERS_UPDATE_PASSANGER"
